var users;
users = [];
var user1;
user1 = { userName: "anis", userId: 122 };
users.push(user1);
var users2;
users = [];
var user2;
user2 = { userName: "Dipu", userId: 128 };
users.push(user2);
console.log(users);
